-- MySQL Script generated by MySQL Workbench
-- Wed Jan 10 15:42:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tiantiantao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tiantiantao` ;

-- -----------------------------------------------------
-- Schema tiantiantao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiantiantao` DEFAULT CHARACTER SET utf8 ;
USE `tiantiantao` ;

-- -----------------------------------------------------
-- Table `tiantiantao`.`OrderForm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`OrderForm` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`OrderForm` (
  `idOrderForm` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `num` VARCHAR(45) NULL COMMENT '订单号码',
  `User_idUser` INT UNSIGNED NOT NULL COMMENT '所属的用户id',
  `recipients` VARCHAR(20) NULL COMMENT '收件人姓名',
  `address` VARCHAR(100) NULL COMMENT '收件人地址',
  `phone` INT(11) NULL COMMENT '收件人联系号码',
  `postcodes` VARCHAR(20) NULL COMMENT '邮编',
  `fare` DOUBLE NULL COMMENT '运费',
  PRIMARY KEY (`idOrderForm`),
  INDEX `fk_OrderForm_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_OrderForm_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `tiantiantao`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`ShoppingCart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`ShoppingCart` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`ShoppingCart` (
  `idShoppingCart` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `OrderForm_idOrderForm` INT UNSIGNED NOT NULL COMMENT '所在的订单id',
  PRIMARY KEY (`idShoppingCart`),
  INDEX `fk_ShoppingCart_OrderForm1_idx` (`OrderForm_idOrderForm` ASC),
  CONSTRAINT `fk_ShoppingCart_OrderForm1`
    FOREIGN KEY (`OrderForm_idOrderForm`)
    REFERENCES `tiantiantao`.`OrderForm` (`idOrderForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`User` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`User` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户表',
  `account` VARCHAR(20) NULL COMMENT '账号',
  `password` VARCHAR(20) NULL COMMENT '密码',
  `name` VARCHAR(45) NULL COMMENT '名称',
  `isVip` TINYINT NULL DEFAULT 0 COMMENT '0 - 非会员\n1 - 会员',
  `ShoppingCart_idShoppingCart` INT UNSIGNED NOT NULL COMMENT '所拥有的购物车id',
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_ShoppingCart1_idx` (`ShoppingCart_idShoppingCart` ASC),
  CONSTRAINT `fk_User_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_idShoppingCart`)
    REFERENCES `tiantiantao`.`ShoppingCart` (`idShoppingCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Category` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Category` (
  `idCategory` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '类别名称',
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`Goods` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`Goods` (
  `idGoods` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT '无' COMMENT '商品名称',
  `descption` VARCHAR(200) NULL DEFAULT '无' COMMENT '商品描述',
  `price` FLOAT NULL DEFAULT 0.00 COMMENT '商品价格',
  `bigImgSrc` VARCHAR(200) NULL DEFAULT '' COMMENT '大图src',
  `Category_idCategory` INT UNSIGNED NOT NULL COMMENT '对应的商品类别id',
  `ShoppingCart_idShoppingCart` INT UNSIGNED NOT NULL COMMENT '所在的购物车id',
  PRIMARY KEY (`idGoods`),
  INDEX `fk_Goods_Category1_idx` (`Category_idCategory` ASC),
  INDEX `fk_Goods_ShoppingCart1_idx` (`ShoppingCart_idShoppingCart` ASC),
  CONSTRAINT `fk_Goods_Category1`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `tiantiantao`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Goods_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_idShoppingCart`)
    REFERENCES `tiantiantao`.`ShoppingCart` (`idShoppingCart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiantiantao`.`SmImgSrc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiantiantao`.`SmImgSrc` ;

CREATE TABLE IF NOT EXISTS `tiantiantao`.`SmImgSrc` (
  `idSmImgSrc` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `src` VARCHAR(200) NULL DEFAULT '' COMMENT 'src',
  `base64` VARCHAR(200) NULL DEFAULT '' COMMENT '缩略图',
  `Goods_idGoods` INT UNSIGNED NOT NULL COMMENT '对应的商品id',
  PRIMARY KEY (`idSmImgSrc`),
  INDEX `fk_SmImgSrc_Goods_idx` (`Goods_idGoods` ASC),
  CONSTRAINT `fk_SmImgSrc_Goods`
    FOREIGN KEY (`Goods_idGoods`)
    REFERENCES `tiantiantao`.`Goods` (`idGoods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
